// <auto-generated />
using GroupManager.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupManager.Migrations
{
    [DbContext(typeof(ManagerContext))]
    [Migration("20220503194019_relation_with_config")]
    partial class relation_with_config
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("GroupManager.DataLayer.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupManager.DataLayer.Models.ManagerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("ManagerConfig");
                });

            modelBuilder.Entity("GroupManager.DataLayer.Models.ManagerConfig", b =>
                {
                    b.HasOne("GroupManager.DataLayer.Models.Group", "Group")
                        .WithOne("ManagerConfig")
                        .HasForeignKey("GroupManager.DataLayer.Models.ManagerConfig", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupManager.DataLayer.Models.Group", b =>
                {
                    b.Navigation("ManagerConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
