name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run
      run: dotnet run
    #- name: Status
    #  run: systemctl status groupManager.service
