name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Stop Service
      run: systemctl stop groupmanager.service
    - name: Build
      run: dotnet build
    - name: publish
      run: dotnet publish -c Release --self-contained --runtime linux-x64
    - name: Run
      run: systemctl start groupmanager.service
      
 
